{
 "title": "Event Booking Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "Сервис", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Динамика активных запросов по серверам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{service_name=~\"$service\"}) by (instance)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "График 95-го (или 99-го) перцентиля",
   "type": "timeseries",
   "description": "Показывает время, в которое укладывается 95% всех запросов.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущая очередь",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{service_name=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{service_name=~\"$service\"}[5m])) / sum(rate(http_server_request_duration_seconds_count{service_name=~\"$service\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=~\"$service\", http_response_status_code=~\"[45]..\"}[5m]))\r\n/\r\nsum(rate(http_server_request_duration_seconds_count{service_name=~\"$service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий RPS",
   "type": "stat",
   "description": "Показывает текущую нагрузку на сервер в виде одной большой цифры.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=~\"$service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 2xx Status Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=~\"$service\", http_response_status_code=~\"2..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS с разбивкой по HTTP-статусам (График ошибок)",
   "type": "timeseries",
   "description": "Помогает увидеть, если пошли ошибки 5xx или 4xx.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=~\"$service\"}[5m])) by (status)\r\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{service_name=~\"$service\"}[1m])) / sum(rate(http_server_request_duration_seconds_count{service_name=~\"$service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS с разбивкой по эндпоинтам (путям)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=~\"$service\"}[5m])) by (route)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=~\"$service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}