<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Events.Application\Events.Application.csproj" />
      <ProjectReference Include="..\Events.Domain\Events.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.12" />
      <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
      <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.22.0" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Events.UnitTests" />
        <InternalsVisibleTo Include="Events.IntegrationTests" />
    </ItemGroup>

</Project>
