<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.2.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Bookings.Domain\Bookings.Domain.csproj" />
      <ProjectReference Include="..\..\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Bookings.UnitTests" />
    </ItemGroup>

</Project>
