@Events_Api_HostAddress = http://localhost:5130/api

### Получить список событий
GET {{Events_Api_HostAddress}}/events
Accept: application/json

### Получить событие по идентификатору
GET {{Events_Api_HostAddress}}/events/1
Accept: application/json

### Создать событие
POST {{Events_Api_HostAddress}}/events
Content-Type: application/json

{
  "id": 1,
  "title": "Н. Римский-Корсаков «Снегурочка»",
  "description": "опера в двух действиях, продолжительность: 2 часа 20 минут с одним антрактом",
  "startAt": "2026-05-03T15:00:00",
  "endAt": "2026-05-03T17:20:00"
}

### Обновить событие
PUT {{Events_Api_HostAddress}}/events/1
Content-Type: application/json

{
  "title": "А. Адан «Жизель»",
  "description": "балет в двух действиях, продолжительность: 2 часа с одним антрактом",
  "startAt": "2026-05-04T18:00:00",
  "endAt": "2026-05-04T20:00:00"
}

### Удалить событие
DELETE {{Events_Api_HostAddress}}/events/1
Accept: application/json